# Generated by Django 6.0.1 on 2026-02-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adres e-mail kontaktu', max_length=254, verbose_name='Email')),
                ('name', models.CharField(help_text='Imię/nazwa kontaktu', max_length=200, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('paused', 'Wstrzymany'), ('completed', 'Zakończony')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mailing_lists.mailinglist', verbose_name='Mailing List')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['mailing_list', 'name'],
                'unique_together': {('mailing_list', 'email')},
            },
        ),
    ]
