# Generated by Django 6.0.1 on 2026-02-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_lists', '0002_contact'),
        ('settings', '0004_emailfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wewnętrzna nazwa kampanii', max_length=200, verbose_name='Nazwa kampanii')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('scheduled', 'Zaplanowana'), ('active', 'Aktywna'), ('paused', 'Wstrzymana'), ('completed', 'Zakończona')], default='draft', help_text='Aktualny status kampanii', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('email_account', models.ForeignKey(blank=True, help_text='Konto email z którego zostanie wysłana kampania', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='settings.emailaccount', verbose_name='Konto email')),
                ('footer', models.ForeignKey(blank=True, help_text='Stopka dodawana do każdej wiadomości', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='settings.emailfooter', verbose_name='Stopka')),
                ('mailing_list', models.ForeignKey(blank=True, help_text='Lista kontaktów do których zostanie wysłana kampania', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='mailing_lists.mailinglist', verbose_name='Lista mailingowa')),
            ],
            options={
                'verbose_name': 'Kampania',
                'verbose_name_plural': 'Kampanie',
                'ordering': ['-created_at'],
            },
        ),
    ]
