# Generated by Django 6.0.1 on 2026-02-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nazwa ustawienia (np. 'API Key', 'Endpoint')", max_length=200)),
                ('text', models.TextField(help_text='Wartość ustawienia', verbose_name='Wartość')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.apitype', verbose_name='API Type')),
            ],
        ),
    ]
