# Generated by Django 6.0.1 on 2026-02-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisetting',
            name='api_type',
            field=models.ForeignKey(help_text='Wybierz typ API (np. OpenAI, Anthropic)', on_delete=django.db.models.deletion.CASCADE, to='settings.apitype', verbose_name='API Type'),
        ),
        migrations.AlterField(
            model_name='apisetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='apisetting',
            name='name',
            field=models.CharField(help_text='Twoja wewnętrzna nazwa klucza API', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='apisetting',
            name='text',
            field=models.TextField(help_text='Klucz API lub inny tekst konfiguracyjny', verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='apisetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
