# Generated by Django 6.0.1 on 2026-02-15 10:07

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_apisetting_api_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adres email konta', max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(help_text="Wewnętrzna nazwa konta (np. 'Sprzedaż 1')", max_length=200, verbose_name='Name/Alias')),
                ('from_name', models.CharField(help_text="Imię/nazwa nadawcy wyświetlana w emailu (np. 'Jan z Firmy')", max_length=200, verbose_name='From Name')),
                ('smtp_host', models.CharField(help_text="Serwer SMTP (np. 'smtp.domena.pl')", max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, help_text='Port SMTP (zazwyczaj 587 dla TLS lub 465 dla SSL)', verbose_name='SMTP Port')),
                ('smtp_username', models.CharField(help_text='Nazwa użytkownika SMTP (często ten sam email)', max_length=255, verbose_name='SMTP Username')),
                ('smtp_password', encrypted_model_fields.fields.EncryptedTextField(help_text='Hasło SMTP (zaszyfrowane)', verbose_name='SMTP Password')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Użyj TLS dla SMTP', verbose_name='SMTP Use TLS')),
                ('imap_host', models.CharField(help_text="Serwer IMAP (np. 'imap.domena.pl')", max_length=255, verbose_name='IMAP Host')),
                ('imap_port', models.IntegerField(default=993, help_text='Port IMAP (zazwyczaj 993 dla SSL)', verbose_name='IMAP Port')),
                ('imap_username', models.CharField(help_text='Nazwa użytkownika IMAP (często ten sam email)', max_length=255, verbose_name='IMAP Username')),
                ('imap_password', encrypted_model_fields.fields.EncryptedTextField(help_text='Hasło IMAP (zaszyfrowane)', verbose_name='IMAP Password')),
                ('imap_use_ssl', models.BooleanField(default=True, help_text='Użyj SSL dla IMAP', verbose_name='IMAP Use SSL')),
                ('is_active', models.BooleanField(default=True, help_text='Czy konto jest aktywne', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
