# Generated by Django 6.0.1 on 2026-02-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_emailaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Np. 'Stopka promocyjna', 'Stopka standard'", max_length=200, verbose_name='Nazwa stopki')),
                ('html_content', models.TextField(help_text='Kod HTML stopki wyświetlany pod treścią emaila', verbose_name='Treść HTML')),
                ('is_default', models.BooleanField(default=False, help_text='Czy ta stopka jest domyślna dla tego konta', verbose_name='Domyślna stopka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footers', to='settings.emailaccount', verbose_name='Konto email')),
            ],
            options={
                'verbose_name': 'Stopka email',
                'verbose_name_plural': 'Stopki email',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
